/*
 * TypingArea.tsx
 *
 * This is THE core component of the entire typing test application.
 * This is where the user actually does the typing.
 *
 * This component handles:
 * 1. Displaying the text to be typed with color-coded characters
 * 2. Capturing keyboard input and comparing it to the expected characters
 * 3. Tracking the current position (word index, character index)
 * 4. Detecting typos and marking them in red
 * 5. Playing sound effects for correct/incorrect keystrokes
 * 6. Ghost mode: Showing a semi-transparent blue caret that races at
 *    the pace of the user's best previous run
 * 7. Smart scrolling: Automatically scrolling the text to keep the
 *    current word visible near the top of the container
 * 8. A blinking yellow caret that shows where you're about to type
 * 9. Click-to-focus overlay when the component is not focused
 * 10. Support for Hindi text using Intl.Segmenter for proper grapheme handling
 *
 * This is a complex component with a lot of state management and
 * side effects, so we use useCallback and useMemo extensively to
 * optimize performance and prevent unnecessary re-renders.
 */

import React, { useEffect, useRef, useCallback, useState, useMemo } from 'react'
import clsx from 'clsx'
import useStore from '../store'

/*
 * IProps interface
 *
 * Defines the props that this component receives from its parent (App.tsx).
 * We extend React.ComponentProps<'div'> so all standard div props are available,
 * but we omit 'onFocus' and 'onBlur' because we handle focus ourselves.
 *
 * text: The text that the user is supposed to type (generated by App.tsx)
 * onStart: Callback fired when the user makes their first keystroke
 * onFinish: Callback fired when the test should end (time up or all words typed)
 */
interface IProps extends Omit<
  React.ComponentProps<'div'>,
  'onFocus' | 'onBlur'
> {
  text: string
  onStart: () => void
  onFinish: () => void
}

/*
 * TypingArea component
 *
 * This is the main typing interface component.
 * It uses React.memo-like optimization through useMemo and useCallback
 * to avoid unnecessary re-renders during fast typing.
 *
 * @param text - The text to display and type
 * @param onStart - Callback when first key is pressed
 * @param onFinish - Callback when test should end
 * @param props - Any additional div props
 */
const TypingArea = ({ text, onStart, onFinish, ...props }: IProps) => {
  /*
   * ============================================================
   * STATE VARIABLES
   * ============================================================
   *
   * Local state for the typing area. These track where the user is
   * in the text and what mistakes they've made.
   */

  /*
   * currWordIndex: Which word the user is currently on.
   * Starts at 0 (first word) and increments when the user presses space.
   */
  const [currWordIndex, setCurrWordIndex] = React.useState(0)

  /*
   * currLetterIndex: Which character within the current word the user is on.
   * Starts at 0 and increments with each correct (or incorrect) keystroke.
   * Resets to 0 when moving to the next word.
   */
  const [currLetterIndex, setCurrLetterIndex] = React.useState(0)

  /*
   * typos: A Set of strings in the format "wordIndex,charIndex" that tracks
   * which characters were typed incorrectly. We use a Set instead of an array
   * because checking membership (has) is O(1) which is faster than array includes.
   * The string key format is a template literal: `${widx},${lidx}`
   *
   * This is used to color incorrect characters in red.
   */
  const [typos, setTypos] = React.useState(new Set<`${number},${number}`>())

  /*
   * isFocused: Whether the typing area currently has focus.
   * When not focused, we show a translucent overlay with a message
   * to click or press any key to focus.
   */
  const [isFocused, setIsFocused] = React.useState(true)

  /*
   * Ghost mode state variables.
   * ghostWordIndex and ghostLetterIndex track where the ghost caret
   * should be displayed, which advances based on the recorded keystrokes
   * from the best previous run.
   */
  const [ghostWordIndex, setGhostWordIndex] = useState(0)
  const [ghostLetterIndex, setGhostLetterIndex] = useState(0)

  /*
   * ============================================================
   * REFS
   * ============================================================
   *
   * Refs are like state variables that don't trigger re-renders when changed.
   * They're perfect for values that change frequently but don't affect the UI.
   */

  /*
   * testStartTime: The timestamp (Date.now()) when the user made their first
   * keystroke. Used to calculate relative timestamps for keystroke recording
   * and for syncing the ghost mode replay.
   */
  const testStartTime = useRef<number>(0)

  /*
   * ghostTimerRef: Stores the requestAnimationFrame ID for the ghost mode
   * animation loop. We need this to cancel the animation when the test resets.
   */
  const ghostTimerRef = useRef<number | null>(null)

  /*
   * containerRef: Reference to the outer div that receives keyboard input.
   * Used to programmatically focus/unfocus the typing area.
   */
  const containerRef = useRef<HTMLDivElement>(null)

  /*
   * wordsContainerRef: Reference to the inner div that holds the word elements.
   * Used for the smart scrolling feature to calculate offsets.
   */
  const wordsContainerRef = useRef<HTMLDivElement>(null)

  /*
   * translateY: The amount of vertical scroll offset (in pixels) applied to
   * the words container. Updated by the smart scrolling logic to keep the
   * current word visible.
   */
  const [translateY, setTranslateY] = useState(0)

  /*
   * Read config and actions from the Zustand store.
   * We read these at the component level so they're available everywhere.
   */
  const { config, incrStat, recordKeystroke, getBestGhostRun } = useStore()

  /*
   * Get the best ghost run (memoized).
   * This is computed once when the component mounts or when ghost mode
   * or the ghost run data changes. We use useMemo to avoid recalculating
   * on every render.
   *
   * If ghost mode is disabled, this returns null.
   */
  const ghostRun = useMemo(
    () => (config.ghostMode ? getBestGhostRun() : null),
    [config.ghostMode, getBestGhostRun],
  )

  /*
   * totalTypedChars: A mutable counter of total characters typed across
   * all words. Used for keystroke recording (to know the absolute character
   * index in the text). This is a ref because it changes on every keystroke
   * and we don't want to cause re-renders.
   */
  const totalTypedChars = useRef(0)

  /*
   * ============================================================
   * AUDIO (Web Audio API)
   * ============================================================
   *
   * We use the Web Audio API to generate synthetic beep sounds for keystrokes.
   * This is much more reliable than using HTMLAudioElement with audio files
   * because:
   * 1. No external files to load
   * 2. Can play overlapping sounds (rapid typing)
   * 3. Low latency
   * 4. Works without any audio files
   *
   * The audio context is created lazily (first time a sound is played)
   * because browsers require user interaction before creating AudioContexts.
   */

  /*
   * audioCtx: The Web Audio API AudioContext instance.
   * Created lazily when the first sound is played.
   * Stored as a ref so it persists across renders.
   */
  const audioCtx = useRef<AudioContext | null>(null)

  /*
   * playSyntheticSound
   *
   * Plays a synthetic beep sound for keystroke feedback.
   *
   * For correct keystrokes:
   *   - Uses a sine wave (smooth, pleasant tone)
   *   - Frequency drops from 800Hz to 400Hz over 50ms
   *   - Volume is low (0.1 gain)
   *
   * For incorrect keystrokes (typos):
   *   - Uses a sawtooth wave (harsher, more noticeable tone)
   *   - Frequency drops from 150Hz to 100Hz over 100ms
   *   - Volume is slightly higher (0.2 gain)
   *   - Longer duration (100ms vs 50ms)
   *
   * We use exponentialRampToValueAtTime for smooth frequency/gain transitions.
   *
   * @param isError - Whether this is a typo (error) sound or a correct sound
   */
  const playSyntheticSound = useCallback(
    (isError: boolean = false) => {
      /*
       * Don't play if sound is disabled in settings.
       */
      if (!config.soundEnabled) return

      try {
        /*
         * Create the AudioContext lazily on first use.
         * Some browsers block AudioContext creation before user interaction,
         * so we can't create it at component mount time.
         * We also support the webkit prefix for older Safari versions.
         */
        if (!audioCtx.current) {
          audioCtx.current = new (
            window.AudioContext || (window as any).webkitAudioContext
          )()
        }

        const ctx = audioCtx.current

        /*
         * Create an oscillator (sound generator) and a gain node (volume control).
         * The oscillator generates the raw waveform, and the gain node controls
         * how loud it is. We connect them in series: oscillator -> gain -> speakers.
         */
        const osc = ctx.createOscillator()
        const gainNode = ctx.createGain()

        osc.connect(gainNode)
        gainNode.connect(ctx.destination)

        if (isError) {
          /*
           * ERROR SOUND: Harsh sawtooth wave, low frequency, short duration.
           * The sawtooth wave has a buzzy, unpleasant quality that makes
           * errors immediately noticeable even without looking at the screen.
           */
          osc.type = 'sawtooth'
          osc.frequency.setValueAtTime(150, ctx.currentTime)
          osc.frequency.exponentialRampToValueAtTime(100, ctx.currentTime + 0.1)

          gainNode.gain.setValueAtTime(0.2, ctx.currentTime)
          gainNode.gain.exponentialRampToValueAtTime(
            0.01,
            ctx.currentTime + 0.1,
          )

          osc.start(ctx.currentTime)
          osc.stop(ctx.currentTime + 0.1)
        } else {
          /*
           * CORRECT SOUND: Smooth sine wave, higher frequency, shorter duration.
           * The sine wave is pleasant and non-intrusive.
           * The frequency drops from 800Hz to 400Hz over 50ms, creating a
           * subtle "ding" effect that confirms the keystroke was correct.
           */
          osc.type = 'sine'
          osc.frequency.setValueAtTime(800, ctx.currentTime)
          osc.frequency.exponentialRampToValueAtTime(
            400,
            ctx.currentTime + 0.05,
          )

          gainNode.gain.setValueAtTime(0.1, ctx.currentTime)
          gainNode.gain.exponentialRampToValueAtTime(
            0.01,
            ctx.currentTime + 0.05,
          )

          osc.start(ctx.currentTime)
          osc.stop(ctx.currentTime + 0.05)
        }
      } catch (e) {
        /*
         * If the Audio API fails for any reason (unsupported browser,
         * disabled audio, etc.), we silently catch the error.
         * The typing test continues to work without sound.
         */
        console.error('Audio API error:', e)
      }
    },
    [config.soundEnabled],
  )

  /*
   * Split the text into words (by spaces).
   * This is a simple array of strings.
   */
  const words = text.split(' ')

  /*
   * Intl.Segmenter for grapheme-based segmentation.
   *
   * This is CRITICAL for Hindi language support.
   * Hindi uses Devanagari script where characters can be composed of
   * multiple Unicode code points (e.g., "का" = क + ा + ा).
   *
   * A simple string.split('') would break Hindi text into individual
   * code points instead of visual characters (graphemes).
   * Intl.Segmenter correctly identifies grapheme clusters, so each
   * Hindi character is treated as one unit for typing purposes.
   *
   * We memoize this because creating a new Segmenter is expensive.
   */
  const segmenter = useMemo(
    () =>
      new Intl.Segmenter(config.language === 'hindi' ? 'hi' : 'en', {
        granularity: 'grapheme',
      }),
    [config.language],
  )

  /*
   * wordGraphemes
   *
   * This is a 2D array where:
   * - The outer array represents each word
   * - The inner array represents each visual character (grapheme) in that word
   *
   * For English: [["t", "h", "e"], ["c", "a", "t"], ...]
   * For Hindi: [["क", "ा"], ["र", "्", "म"], ...]
   *
   * This is memoized because it only changes when the text or language changes.
   * Computing graphemes is expensive and we don't want to do it on every render.
   */
  const wordGraphemes = useMemo(() => {
    return words.map((word) =>
      Array.from(segmenter.segment(word)).map((s) => s.segment),
    )
  }, [words, segmenter])

  /*
   * ============================================================
   * GHOST MODE EFFECT
   * ============================================================
   *
   * This effect runs the ghost mode animation loop.
   * Ghost mode shows a semi-transparent blue caret that moves through
   * the text at the pace of the user's best previous run.
   *
   * How it works:
   * 1. When the test starts (testStartTime > 0), begin the animation
   * 2. Use requestAnimationFrame for smooth 60fps animation
   * 3. Each frame, compare the current time to the recorded keystroke timestamps
   * 4. Advance the ghost caret to match the recorded typing pace
   * 5. Continue until all keystrokes are replayed
   *
   * This creates the effect of "racing" against your past self.
   */
  useEffect(() => {
    /*
     * Only start ghost mode if:
     * - The test has started (testStartTime > 0)
     * - A valid ghost run exists (ghostRun with keystrokes)
     */
    if (testStartTime.current > 0 && ghostRun && ghostRun.keystrokes) {
      let currentIdx = 0

      /*
       * runGhost: The animation frame callback.
       * Recalculates the ghost caret position based on elapsed time.
       */
      const runGhost = () => {
        /*
         * Calculate how much time has passed since the test started.
         * This is compared to the original keystroke timestamps.
         */
        const now = Date.now() - testStartTime.current

        /*
         * Advance through all keystrokes that should have been typed by now.
         * We check each recorded keystroke's timestamp against the current time.
         */
        while (
          currentIdx < ghostRun.keystrokes.length &&
          ghostRun.keystrokes[currentIdx].timestamp <= now
        ) {
          /*
           * Convert the absolute character position to word/letter indices.
           * We iterate through the words, counting characters until we find
           * which word and letter this character position maps to.
           *
           * The +1 accounts for the space between words.
           */
          const charPos = ghostRun.keystrokes[currentIdx].charIndex
          let count = 0
          let gWord = 0
          let gLet = 0

          for (let i = 0; i < wordGraphemes.length; i++) {
            if (count + wordGraphemes[i].length + 1 > charPos) {
              gWord = i
              gLet = charPos - count
              break
            }
            count += wordGraphemes[i].length + 1
          }

          /*
           * Update the ghost caret position to this keystroke.
           */
          setGhostWordIndex(gWord)
          setGhostLetterIndex(gLet)
          currentIdx++
        }

        /*
         * If there are more keystrokes to replay, request the next frame.
         * Otherwise, the animation stops automatically.
         */
        if (currentIdx < ghostRun.keystrokes.length) {
          ghostTimerRef.current = requestAnimationFrame(runGhost)
        }
      }

      /*
       * Start the animation loop.
       */
      ghostTimerRef.current = requestAnimationFrame(runGhost)

      /*
       * Cleanup: Cancel the animation frame when the component unmounts
       * or when the dependencies change.
       */
      return () => {
        if (ghostTimerRef.current) cancelAnimationFrame(ghostTimerRef.current)
      }
    }
  }, [testStartTime.current, ghostRun, wordGraphemes])

  /*
   * ============================================================
   * RESET EFFECT
   * ============================================================
   *
   * When the text changes (new test), reset all local state.
   * This effect:
   * 1. Resets the current position to the start
   * 2. Clears all typos
   * 3. Resets ghost caret position
   * 4. Resets scroll position
   * 5. Resets the test start time
   * 6. Resets the character counter
   * 7. Cancels any running ghost animation
   * 8. Focuses the container after a short delay
   */
  useEffect(() => {
    setCurrWordIndex(0)
    setCurrLetterIndex(0)
    setTypos(new Set())
    setGhostWordIndex(0)
    setGhostLetterIndex(0)
    setTranslateY(0)
    testStartTime.current = 0
    totalTypedChars.current = 0
    if (ghostTimerRef.current) cancelAnimationFrame(ghostTimerRef.current)

    /*
     * Focus the typing container after a short delay.
     * The delay ensures the DOM has finished updating before we try to focus.
     * Without this, the focus might not work correctly.
     */
    const focusTimer = setTimeout(() => {
      containerRef.current?.focus()
    }, 100)
    return () => clearTimeout(focusTimer)
  }, [text])

  /*
   * ============================================================
   * GLOBAL CLICK HANDLER EFFECT
   * ============================================================
   *
   * This effect adds a global click handler that focuses the typing area
   * when the user clicks anywhere on the page (except on interactive elements
   * like buttons, inputs, and links).
   *
   * This makes the typing test more user-friendly because you don't have to
   * click directly on the text area to start typing.
   */
  useEffect(() => {
    const handleGlobalClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement
      /*
       * Don't steal focus if the user clicked on interactive elements.
       * We check both the tag name and use closest() to find parent elements.
       * This prevents accidentally stealing focus from buttons in the header.
       */
      if (
        ['INPUT', 'BUTTON', 'A', 'TEXTAREA'].includes(target.tagName) ||
        target.closest('button') ||
        target.closest('input') ||
        target.closest('a')
      ) {
        return
      }
      containerRef.current?.focus()
    }
    window.addEventListener('click', handleGlobalClick)
    return () => window.removeEventListener('click', handleGlobalClick)
  }, [])

  /*
   * ============================================================
   * SMART SCROLLING EFFECT
   * ============================================================
   *
   * This effect automatically scrolls the text up as the user progresses
   * through words, so the current word is always visible near the top of
   * the typing area.
   *
   * It works by:
   * 1. Finding the DOM element of the current word (data-active="true")
   * 2. Measuring its offset from the top of the container
   * 3. If it's scrolled down too far (offsetTop > 60px), scroll up
   * 4. If the user backspaced back up, scroll down again
   *
   * The scrolling is animated with CSS transition (duration-300 ease-out).
   * We use translateY on the container div instead of actual scroll position.
   */
  useEffect(() => {
    if (!wordsContainerRef.current) return

    /*
     * Find the currently active word element using the data-active attribute.
     * We use querySelector instead of managing refs for each word because
     * it's simpler and works with dynamically generated content.
     */
    const activeWordEl = wordsContainerRef.current.querySelector(
      '[data-active="true"]',
    ) as HTMLElement
    if (!activeWordEl) return

    /*
     * Get the vertical offset of the active word within the container.
     */
    const offsetTop = activeWordEl.offsetTop

    /*
     * If the active word has scrolled down more than 60px from the top,
     * scroll the container up to keep it visible.
     * The 8px offset gives a small padding at the top.
     */
    if (offsetTop > 60) {
      setTranslateY(offsetTop - 8)
    } else if (offsetTop < 10 && translateY > 0) {
      /*
       * If the user backspaced and moved back up, scroll back down.
       * This ensures the text doesn't stay scrolled up when you go back.
       * We nudge it by 48px (approximately one line height).
       */
      setTranslateY(Math.max(0, translateY - 48))
    }
  }, [currWordIndex, translateY])

  /*
   * ============================================================
   * KEYBOARD EVENT HANDLER
   * ============================================================
   *
   * handleKeyDown is the main keyboard input handler.
   * It processes every keystroke and determines:
   * - Did the user press Backspace? (go back one character)
   * - Did the user press Space? (advance to next word)
   * - Did the user type a regular character? (check for typos, advance)
   *
   * This function handles the core typing test logic.
   */
  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    /*
     * Ignore modifier key combinations (Ctrl, Meta, Alt).
     * These are typically used for browser shortcuts and we don't want
     * to interfere with them. For example, Ctrl+C for copy should not
     * be treated as typing a 'c' character.
     */
    if (e.ctrlKey || e.metaKey || e.altKey) return

    /*
     * Get the expected characters for the current word.
     */
    const currWordChars = wordGraphemes[currWordIndex] || []

    /*
     * START TEST: If this is the first keypress (word 0, letter 0),
     * fire the onStart callback and record the start time.
     * The start time is used for keystroke timing and ghost mode sync.
     */
    if (e.key.length === 1 && currWordIndex === 0 && currLetterIndex === 0) {
      onStart()
      testStartTime.current = Date.now()
    }

    /*
     * Record every keystroke with its character index and timestamp.
     * This is used for:
     * 1. Generating the per-second chart data
     * 2. Ghost mode replay on future runs
     *
     * The character index is the absolute position in the full text string.
     * The timestamp is relative to the test start time (in milliseconds).
     */
    if (testStartTime.current > 0) {
      recordKeystroke(
        totalTypedChars.current,
        Date.now() - testStartTime.current,
      )
    }

    /*
     * BACKSPACE HANDLER
     *
     * When the user presses Backspace:
     * 1. If we're in the middle of a word, go back one character
     * 2. If we're at the start of a word (but not the first), go to the
     *    previous word and put the cursor at its end
     * 3. Remove the typo marker for the character we're un-typing
     *
     * This allows the user to correct mistakes.
     */
    if (e.key === 'Backspace') {
      /*
       * Play the correct keystroke sound (not the error sound).
       */
      playSyntheticSound()
      if (currLetterIndex > 0) {
        /*
         * Go back one character in the current word.
         */
        setCurrLetterIndex((prev) => prev - 1)
        totalTypedChars.current = Math.max(0, totalTypedChars.current - 1)
        /*
         * Remove the typo marker for this position.
         * This means if the user backspaces over a typo, the red
         * highlighting goes away.
         */
        setTypos((prev) => {
          const newSet = new Set(prev)
          newSet.delete(`${currWordIndex},${currLetterIndex - 1}`)
          return newSet
        })
      } else if (currWordIndex > 0) {
        /*
         * Go to the previous word and put cursor at the end of that word.
         */
        setCurrWordIndex((prev) => prev - 1)
        const prevWordActual = wordGraphemes[currWordIndex - 1]
        setCurrLetterIndex(prevWordActual.length)
        totalTypedChars.current = Math.max(0, totalTypedChars.current - 1)
      }
      e.preventDefault()
      return
    }

    /*
     * SPACE HANDLER
     *
     * When the user presses Space:
     * 1. If cursor is at the start of a word, do nothing (prevent leading spaces)
     * 2. If this is the last word, finish the test
     * 3. Otherwise, advance to the next word and increment the word counter
     *
     * The user MUST have typed at least one character before pressing space.
     * This prevents accidental test completion from double spaces.
     */
    if (e.key === ' ') {
      /*
       * Play the correct sound for advancing to the next word.
       */
      playSyntheticSound()

      /*
       * If the cursor is at position 0 (nothing typed yet), reject the space.
       * This prevents the user from just pressing space to skip words.
       */
      if (currLetterIndex === 0) {
        e.preventDefault()
        return
      }

      /*
       * If this is the last word, finish the test.
       * The user has completed all available words.
       */
      if (currWordIndex === wordGraphemes.length - 1) {
        onFinish()
        return
      }

      /*
       * Advance to the next word, reset the letter index.
       * Increment the word counter and the total character counter.
       * The space itself counts as one character for keystroke tracking.
       */
      setCurrWordIndex((prev) => prev + 1)
      setCurrLetterIndex(0)
      totalTypedChars.current += 1
      incrStat('wordCount')
      e.preventDefault()
      return
    }

    /*
     * CHARACTER HANDLER
     *
     * When the user types a regular character (e.key.length === 1):
     * 1. Increment character count
     * 2. Check if the typed character matches the expected character
     * 3. If it matches: play correct sound
     * 4. If it doesn't match: mark as typo, play error sound, increment typo counter
     * 5. Advance the cursor forward
     *
     * We allow up to 5 extra characters beyond the word length (for typos).
     * The extra characters are displayed as "*" in red.
     */
    if (e.key.length === 1) {
      /*
       * Allow the user to keep typing even past the end of the word
       * (up to 5 extra characters). This handles the case where the user
       * types extra characters before pressing space.
       */
      if (currLetterIndex < currWordChars.length + 5) {
        /*
         * Increment the typed character counter in the store.
         */
        incrStat('typedCharCount')
        totalTypedChars.current += 1

        /*
         * Check if this keystroke is a typo.
         * It's a typo if:
         * 1. The character doesn't match the expected character, OR
         * 2. We're past the end of the word (extra characters)
         */
        let isTypo = false
        if (currLetterIndex < currWordChars.length) {
          /*
           * We're within the word bounds, so compare characters.
           */
          const expectedChar = currWordChars[currLetterIndex]
          if (expectedChar !== e.key) {
            isTypo = true
          }
        } else {
          /*
           * We're past the end of the word, so anything typed is a typo.
           */
          isTypo = true
        }

        /*
         * Handle typo vs correct keystroke.
         */
        if (isTypo) {
          /*
           * Play the error sound and record the typo position.
           */
          playSyntheticSound(true)
          setTypos((prev) =>
            new Set(prev).add(`${currWordIndex},${currLetterIndex}`),
          )
          incrStat('typos')
        } else {
          /*
           * Play the correct sound.
           */
          playSyntheticSound()
        }

        /*
         * Advance the cursor forward by one character.
         */
        setCurrLetterIndex((prev) => prev + 1)
      }
      e.preventDefault()
    }
  }
  return (
    <div
      ref={containerRef}
      onKeyDown={handleKeyDown}
      onFocus={() => setIsFocused(true)}
      onBlur={() => setIsFocused(false)}
      role="textbox"
      tabIndex={0}
      className={clsx(
        'flex flex-wrap focus:outline-none relative font-mono text-3xl leading-relaxed outline-none w-full max-h-37.5 overflow-hidden',
        config.language === 'hindi' ? 'font-sans' : 'font-mono',
      )}
      {...props}
    >
      {/*
       * Words container div.
       * This inner div uses translateY for smooth scrolling.
       * The transition makes the scroll animation smooth and bouncy.
       * Words are displayed with flex-wrap so they wrap naturally.
       * gap-x-4 and gap-y-4 provide spacing between words.
       */}
      <div
        ref={wordsContainerRef}
        className="flex flex-wrap transition-transform duration-300 ease-out w-full gap-x-4 gap-y-4"
        style={{ transform: `translateY(-${translateY}px)` }}
      >
        {/*
         * Iterate through all words and their graphemes (visual characters).
         */}
        {wordGraphemes.map((wordChars, widx) => {
          /*
           * Determine the word status:
           * isCurrWord: The active word being typed
           * isPastWord: A completed word (cursor has moved past it)
           * isGhostWord: The word where the ghost caret currently is
           */
          const isCurrWord = widx === currWordIndex
          const isPastWord = widx < currWordIndex
          const isGhostWord = config.ghostMode && widx === ghostWordIndex

          return (
            /*
             * Each word is rendered as a <div>.
             * The data-active attribute is used by the smart scrolling effect
             * to find the current word's DOM position.
             * Past words are dimmed to 30% opacity to show progress.
             * Current words are fully visible.
             */
            <div
              key={widx}
              data-active={isCurrWord}
              className={clsx(
                'relative flex transition-all duration-200 rounded',
                isPastWord ? 'opacity-30' : 'opacity-100',
                isCurrWord && 'text-text',
              )}
            >
              {/*
               * Render each character in the word as a <span>.
               * The character color depends on whether it's been typed
               * and whether it was typed correctly.
               */}
              {wordChars.map((char, lidx) => {
                /*
                 * Check if this character was typed as a typo.
                 * We look up the position in the Set using the template literal key.
                 */
                const isTypo = typos.has(`${widx},${lidx}`)

                /*
                 * Check if this character has been typed yet.
                 * A character is "typed" if:
                 * - The word is a past word (all characters are typed), OR
                 * - The current word and the cursor has passed this character
                 */
                const isTyped =
                  isPastWord || (isCurrWord && lidx < currLetterIndex)

                return (
                  /*
                   * Each character span with conditional styling:
                   * - Un-typed: muted gray color
                   * - Typed correctly: white color
                   * - Typo: red color with red bottom border
                   *
                   * The duration-100 transition makes color changes snappy.
                   */
                  <span
                    key={lidx}
                    className={clsx(
                      'transition-colors duration-100 relative',
                      !isTyped && 'text-text-muted',
                      isTyped && !isTypo && 'text-text',
                      isTypo && 'text-error border-b-2 border-error',
                    )}
                  >
                    {char}

                    {/*
                     * USER CARET (blinking yellow cursor)
                     *
                     * Shown when:
                     * - The typing area is focused
                     * - This is the current word
                     * - This character is the current cursor position
                     *
                     * The caret is a thin (0.75px) yellow vertical bar
                     * with a glow effect (box-shadow).
                     * It blinks using the animate-blink CSS animation.
                     */}
                    {isFocused && isCurrWord && lidx === currLetterIndex && (
                      <div className="absolute -left-px top-1 bottom-1 w-0.75 bg-brand animate-blink rounded-full shadow-[0_0_8px_rgba(234,179,8,0.5)] z-30" />
                    )}

                    {/*
                     * GHOST CARET (semi-transparent blue cursor)
                     *
                     * Shown when ghost mode is enabled and the ghost caret
                     * is positioned at this character in the current word.
                     *
                     * The ghost caret is a thin blue vertical bar
                     * with a subtle blue glow.
                     * It's semi-transparent (opacity 50%) to distinguish
                     * it from the user's own caret.
                     */}
                    {config.ghostMode &&
                      isGhostWord &&
                      lidx === ghostLetterIndex && (
                        <div className="absolute -left-px top-1 bottom-1 w-0.75 bg-blue-500/50 rounded-full shadow-[0_0_8px_rgba(59,130,246,0.3)] z-20" />
                      )}
                  </span>
                )
              })}

              {/*
               * EXTRA CHARACTERS (typo overflow)
               *
               * If the user has typed more characters than the word has,
               * we display them as red asterisks (*) below the word.
               * This shows the user they've typed extra characters.
               * Up to the number of extra characters are shown.
               */}
              {isCurrWord &&
                currLetterIndex >= wordChars.length &&
                Array.from({ length: currLetterIndex - wordChars.length }).map(
                  (_, extraIdx) => (
                    <span
                      key={`extra-${extraIdx}`}
                      className="text-error border-b-2 border-error opacity-70"
                    >
                      *
                    </span>
                  ),
                )}

              {/*
               * END-OF-WORD CARET (when cursor is past the word)
               *
               * When the user has typed all characters in a word (or more),
               * the caret moves to end of the word to indicate they should
               * press space to continue.
               */}
              {isFocused &&
                isCurrWord &&
                currLetterIndex >= wordChars.length && (
                  <div className="absolute -right-[2px] top-1 bottom-1 w-[3px] bg-brand animate-blink rounded-full shadow-[0_0_8px_rgba(234,179,8,0.5)] z-30" />
                )}

              {/*
               * GHOST END-OF-WORD CARET
               * Same as above but for the ghost caret.
               */}
              {config.ghostMode &&
                isGhostWord &&
                ghostLetterIndex >= wordChars.length && (
                  <div className="absolute -right-[2px] top-1 bottom-1 w-[3px] bg-blue-500/50 rounded-full shadow-[0_0_8px_rgba(59,130,246,0.3)] z-20" />
                )}
            </div>
          )
        })}
      </div>

      {/*
       * UNFOCUSED OVERLAY
       *
       * When the typing area is not focused, we show a translucent overlay
       * with a message telling the user to click or press any key.
       * This improves the user experience by making it clear how to start.
       *
       * The overlay has a backdrop blur effect for visual depth.
       */}
      {!isFocused && (
        <div className="absolute inset-0 z-50 cursor-text flex items-center justify-center bg-bg/40 backdrop-blur-[2px] transition-all">
          <div className="bg-bg-secondary px-6 py-3 rounded-lg border border-neutral-700 shadow-xl text-text font-sans flex items-center gap-3">
            <span className="animate-pulse">
              Click here or press any key to focus
            </span>
          </div>
        </div>
      )}
    </div>
  )
}

export default TypingArea
